### PR TITLE
update polish translation for J 4.1.0

### PR DESCRIPTION
**Pull request by wojsmol**
cc @zwiastunsw

### CODE REVIEW

**Review by tecpromotion — APPROVED** [review]
thanks @wojsmol

**Comment by wojsmol** [comment]
@tecpromotion Please run synchr4onisation of Polish translation with crowdin - there is manually triggered `.github/workflows/local-upload-polish.yml` for that.

**Comment by tecpromotion** [comment]
> @tecpromotion Please run synchr4onisation of Polish translation with crowdin - there is manually triggered `.github/workflows/local-upload-polish.yml` for that.

@wojsmol it runs automatically after merge

**Comment by tecpromotion** [comment]
it does not!
i've started the gha manually. it#s done now. thanks @wojsmol

**Comment by wojsmol** [comment]
All of the  `.github/workflows/local-upload-*.yml` workflows are using
```yml
on:
  workflow_dispatch:
```
so are manually triggered.

**Comment by tecpromotion** [comment]
yes, i have to improve this asap. thanks

**Pull request merged**
