### PR TITLE
Update polish translation to 4.2.0.1

### PR DESCRIPTION
**Pull request by wojsmol**

### CODE REVIEW

**Comment by wojsmol** [comment]
Here the new workflow will fail to add comment because of token perrmision

**Comment by wojsmol** [comment]
@tecpromotion What do you man by assigning me here?

**Comment by tecpromotion** [comment]
> @tecpromotion What do you man by assigning me here?

Shouldn't the workflow go through?

**Comment by wojsmol** [comment]
As commented in https://github.com/joomla/core-translations/pull/382#issuecomment-1220623506 - here we have a permissions issue because this PR is created from fork and uses default  github token witch in this case have only read permissions. In addition to that we have errors in other transudation and in that case workflow will be always set as failed

**Comment by zero-24** [comment]
so we have to Register an new bot or ask @HLeithner for an api token for the translation-bot?

**Comment by wojsmol** [comment]
@zero-24 PAT will be nought - or a reset of GHA token permission - see https://github.com/joomla/core-translations/pull/381#discussion_r950115731

**Comment by HLeithner** [comment]
the github workflow has normally own permission to comment iirc maybe the workflow have to request them

**Comment by wojsmol** [comment]
@HLeithner @zero-24 Not if a workflow run in trigged by PR from a fork of repo. In that case standard `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} ` have only a read permission.

**Comment by HLeithner** [comment]
adding a comment seems to be not possible as @wojsmol found out looking at https://github.com/marketplace/actions/add-pr-comment

so I wouldn't comment just fail

**Comment by HLeithner** [comment]
as alternative we can run it with drone

**Comment by wojsmol** [comment]
@HLeithner Adding a comment in this case is passible if we pass a token with appropriate write access - see https://github.com/peter-evans/create-or-update-comment/issues/103#issuecomment-1041057863. We can also just fail the check.

**Comment by wojsmol** [comment]
Please make a decision and I can adapt this workflow is a short time.

**Comment by wojsmol** [comment]
Please also see https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/

**Comment by HLeithner** [comment]
I created a now secret called "WRITE_COMMENTS" please try if it works.

**Comment by wojsmol** [comment]
I can't get this to work. We can switch from `pull_request` to `pull_request_target` in the `main` branch and then update this PR branch.

**Comment by tecpromotion** [comment]
@wojsmol 👍 for `pull_request_target `
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

**Comment by wojsmol** [comment]
I find other way:
- https://github.com/JoomlaPolska/core-translations/pull/4
- https://github.com/JoomlaPolska/core-translations/pull/5
Comment  is added using: 
```
on:
  workflow_run:
    workflows: ["En_GBLocalise in translations"]
```
this trigger only runs from workflow on main branch

**Comment by tecpromotion** [comment]
> If this looks ok then I can create separate PR for this.

It looks OK to me. Please create a PR. Thank you @wojsmol

**Comment by wojsmol** [comment]
PR created https://github.com/joomla/core-translations/pull/385

**Review by tecpromotion — APPROVED** [review]

**Comment by wojsmol** [comment]
@HLeithner You can delete this additional secret.

**Comment by tecpromotion** [comment]
> @HLeithner You can delete this additional secret.

The "WRITE_COMMENTS" secret?
I can do that of course.

**Comment by wojsmol** [comment]
@tecpromotion Yes, it's not used with workflow_run approach. Deleting associated PAT will be also nice.

**Comment by tecpromotion** [comment]
The secret is deleted.

Can't see any associated PAT.

**Pull request merged**
