### PR TITLE
Update de-AT, de-DE, de-LI and de-LU

### PR DESCRIPTION
**Pull request by zero-24**
cc @tecpromotion

### CODE REVIEW

**Comment by conconnl** [comment]
Why is there a script file, while any other package doesn’t have that?

**Comment by zero-24** [comment]
> Why is there a script file, while any other package doesn’t have that?

Cause we need a script file to remove the 3.x style language files and to make sure the packs can only be installed in 4.x.

**Comment by conconnl** [comment]
Wouldn't that mean every language needs that and the project should provide it as source?

**Comment by zero-24** [comment]
I personally would say yes but that should not block updating the exising de-* language translations to crowdin.

Thanks for merging here.

**Comment by conconnl** [comment]
Correct, explanation is important to be able to answer others when they ask about it. 
Thanks for the update.

**Pull request merged**
