### PR TITLE
ru-RU Installation (4.3.2)

### PR DESCRIPTION
**Pull request by Kostelano**
Hi! Updated ru-RU files of the Joomla installation directory.

### CODE REVIEW

**Comment by tecpromotion** [comment]
@Kostelano there is a GitHub Action that downloads data from this REPO: https://github.com/JPathRu/localisation

It would be better if you keep the changes there up to date.
Or is there a special reason why nothing here has been adapted to 4.3.x yet?

**Comment by Kostelano** [comment]
The last 2 times for sure (but possibly more) I sent the PR to this repository, since we agreed on this in the mail correspondence (May, 2022). There I voiced the problem that we are not translating to Crowdin, but only to GitHub. But it was stubbornly synchronized into this repository from Crowdin.

If at the moment synchronization is implemented from our repository (and not from Crowdin), then there are no problems, the PR can be closed.

**Comment by tecpromotion** [comment]
The following GA runs daily: https://github.com/joomla/core-translations/blob/main/.github/workflows/remote-get-russian.yml

After that, another GA runs and pushed this towards crowdin.
For the Russian language files, they are only uploaded towards crowdin and not downloaded from there.

**Comment by Kostelano** [comment]
Hello!

So-ssss, as you might expect (because I did PR for the installation files before), [everything was transferred](https://github.com/joomla/core-translations/commit/dc41e37fff0c7c58b8b58f2a6890f580afdba85f) to this repository, except for the installation files.

Screenshot_1

What shall we do?

**Pull request closed without merging**
