### PR TITLE
update polish translation for J 4.0.4

### PR DESCRIPTION
**Pull request by zwiastunsw**

### CODE REVIEW

**Review by conconnl — CHANGES_REQUESTED** [review]
The Core Installation files must come from Crowdin, to keep them the same on various lines in the different languages. 
Accepting it isn’t possible as it potentially can break the core installer. 

joomla_v4/translations/core/installation/language/pl-PL/langmetadata.xml

**Comment by wojsmol** [comment]
@conconnl Please see https://github.com/joomla/core-translations/pull/103/commits/bc43f944281d1bca85384217121ff7da6b81f464

**Comment by wojsmol** [comment]
@conconnl Issue was that this togs was changed or something else?

**Comment by conconnl** [comment]
The Crowdin sync will override it again. The PR should never include the Core installation part. 
If needed I can enable the Sync Action and get the files from your repository, then you never have to create PRa anymore.

**Comment by wojsmol** [comment]
I or @zwiastunsw will contact you about sync -we must adapt our build script to don't change this two tags.

**Pull request merged**
